import type { Metadata } from 'next'
import 'react-toastify/dist/ReactToastify.css'
import Header from '../components/home/Header'
import Footer from '../components/home/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  )
}
